enum AppRole {
  super_admin
  pastor
  treasurer
  secretary
  usher
  department_head
  content_editor
}

"""
Boolean expression comparing fields on type "AppRole"
"""
input AppRoleFilter {
  eq: AppRole
  in: [AppRole!]
  is: FilterIs
  neq: AppRole
}

"""A high precision floating point value represented as a string"""
scalar BigFloat

"""
Boolean expression comparing fields on type "BigFloat"
"""
input BigFloatFilter {
  eq: BigFloat
  gt: BigFloat
  gte: BigFloat
  in: [BigFloat!]
  is: FilterIs
  lt: BigFloat
  lte: BigFloat
  neq: BigFloat
}

"""
Boolean expression comparing fields on type "BigFloatList"
"""
input BigFloatListFilter {
  containedBy: [BigFloat!]
  contains: [BigFloat!]
  eq: [BigFloat!]
  is: FilterIs
  overlaps: [BigFloat!]
}

"""An arbitrary size integer represented as a string"""
scalar BigInt

"""
Boolean expression comparing fields on type "BigInt"
"""
input BigIntFilter {
  eq: BigInt
  gt: BigInt
  gte: BigInt
  in: [BigInt!]
  is: FilterIs
  lt: BigInt
  lte: BigInt
  neq: BigInt
}

"""
Boolean expression comparing fields on type "BigIntList"
"""
input BigIntListFilter {
  containedBy: [BigInt!]
  contains: [BigInt!]
  eq: [BigInt!]
  is: FilterIs
  overlaps: [BigInt!]
}

"""
Boolean expression comparing fields on type "Boolean"
"""
input BooleanFilter {
  eq: Boolean
  is: FilterIs
}

"""
Boolean expression comparing fields on type "BooleanList"
"""
input BooleanListFilter {
  containedBy: [Boolean!]
  contains: [Boolean!]
  eq: [Boolean!]
  is: FilterIs
  overlaps: [Boolean!]
}

type ContentItems implements Node {
  """Globally Unique Record Identifier"""
  nodeId: ID!
  id: UUID!
  kind: ContentKind!
  slug: String
  title: String!
  body: String
  imagePath: String
  publishAt: Datetime
  expiresAt: Datetime
}

type ContentItemsConnection {
  edges: [ContentItemsEdge!]!
  pageInfo: PageInfo!
}

type ContentItemsEdge {
  cursor: String!
  node: ContentItems!
}

input ContentItemsFilter {
  id: UUIDFilter
  kind: ContentKindFilter
  slug: StringFilter
  title: StringFilter
  body: StringFilter
  imagePath: StringFilter
  publishAt: DatetimeFilter
  expiresAt: DatetimeFilter
  nodeId: IDFilter

  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [ContentItemsFilter!]

  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [ContentItemsFilter!]

  """Negates a filter"""
  not: ContentItemsFilter
}

input ContentItemsOrderBy {
  id: OrderByDirection
  kind: OrderByDirection
  slug: OrderByDirection
  title: OrderByDirection
  body: OrderByDirection
  imagePath: OrderByDirection
  publishAt: OrderByDirection
  expiresAt: OrderByDirection
}

enum ContentKind {
  announcement
  quote
  page
  activity
}

"""
Boolean expression comparing fields on type "ContentKind"
"""
input ContentKindFilter {
  eq: ContentKind
  in: [ContentKind!]
  is: FilterIs
  neq: ContentKind
}

enum ContentStatus {
  draft
  in_review
  published
  archived
}

"""
Boolean expression comparing fields on type "ContentStatus"
"""
input ContentStatusFilter {
  eq: ContentStatus
  in: [ContentStatus!]
  is: FilterIs
  neq: ContentStatus
}

"""
An opaque string using for tracking a position in results during pagination
"""
scalar Cursor

"""A date without time information"""
scalar Date

"""
Boolean expression comparing fields on type "Date"
"""
input DateFilter {
  eq: Date
  gt: Date
  gte: Date
  in: [Date!]
  is: FilterIs
  lt: Date
  lte: Date
  neq: Date
}

"""
Boolean expression comparing fields on type "DateList"
"""
input DateListFilter {
  containedBy: [Date!]
  contains: [Date!]
  eq: [Date!]
  is: FilterIs
  overlaps: [Date!]
}

"""A date and time"""
scalar Datetime

"""
Boolean expression comparing fields on type "Datetime"
"""
input DatetimeFilter {
  eq: Datetime
  gt: Datetime
  gte: Datetime
  in: [Datetime!]
  is: FilterIs
  lt: Datetime
  lte: Datetime
  neq: Datetime
}

"""
Boolean expression comparing fields on type "DatetimeList"
"""
input DatetimeListFilter {
  containedBy: [Datetime!]
  contains: [Datetime!]
  eq: [Datetime!]
  is: FilterIs
  overlaps: [Datetime!]
}

enum FilterIs {
  NULL
  NOT_NULL
}

"""
Boolean expression comparing fields on type "Float"
"""
input FloatFilter {
  eq: Float
  gt: Float
  gte: Float
  in: [Float!]
  is: FilterIs
  lt: Float
  lte: Float
  neq: Float
}

"""
Boolean expression comparing fields on type "FloatList"
"""
input FloatListFilter {
  containedBy: [Float!]
  contains: [Float!]
  eq: [Float!]
  is: FilterIs
  overlaps: [Float!]
}

"""
Boolean expression comparing fields on type "ID"
"""
input IDFilter {
  eq: ID
}

"""
Boolean expression comparing fields on type "Int"
"""
input IntFilter {
  eq: Int
  gt: Int
  gte: Int
  in: [Int!]
  is: FilterIs
  lt: Int
  lte: Int
  neq: Int
}

"""
Boolean expression comparing fields on type "IntList"
"""
input IntListFilter {
  containedBy: [Int!]
  contains: [Int!]
  eq: [Int!]
  is: FilterIs
  overlaps: [Int!]
}

"""A Javascript Object Notation value serialized as a string"""
scalar JSON

enum MemberStatus {
  visitor
  active
  inactive
  transferred
  deceased
}

"""
Boolean expression comparing fields on type "MemberStatus"
"""
input MemberStatusFilter {
  eq: MemberStatus
  in: [MemberStatus!]
  is: FilterIs
  neq: MemberStatus
}

interface Node {
  """Retrieves a record by `ID`"""
  nodeId: ID!
}

"""Any type not handled by the type system"""
scalar Opaque

"""
Boolean expression comparing fields on type "Opaque"
"""
input OpaqueFilter {
  eq: Opaque
  is: FilterIs
}

"""Defines a per-field sorting order"""
enum OrderByDirection {
  """Ascending order, nulls first"""
  AscNullsFirst

  """Ascending order, nulls last"""
  AscNullsLast

  """Descending order, nulls first"""
  DescNullsFirst

  """Descending order, nulls last"""
  DescNullsLast
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
}

"""The root type for querying data"""
type Query {
  """Retrieve a record of type `ContentItems` by its primary key"""
  contentItemsByPk(
    """The record's `id` value"""
    id: UUID!
  ): ContentItems

  """A pagable collection of type `ContentItems`"""
  contentItemsCollection(
    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Query values in the collection after the provided cursor"""
    after: Cursor

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Filters to apply to the results set when querying from the collection"""
    filter: ContentItemsFilter

    """Sort order to apply to the collection"""
    orderBy: [ContentItemsOrderBy!]
  ): ContentItemsConnection!

  """Retrieve a record by its `ID`"""
  node(
    """The record's `ID`"""
    nodeId: ID!
  ): Node

  """Retrieve a record of type `Sermons` by its primary key"""
  sermonsByPk(
    """The record's `id` value"""
    id: UUID!
  ): Sermons

  """A pagable collection of type `Sermons`"""
  sermonsCollection(
    """Query the first `n` records in the collection"""
    first: Int

    """Query the last `n` records in the collection"""
    last: Int

    """Query values in the collection before the provided cursor"""
    before: Cursor

    """Query values in the collection after the provided cursor"""
    after: Cursor

    """
    Skip n values from the after cursor. Alternative to cursor pagination. Backward pagination not supported.
    """
    offset: Int

    """Filters to apply to the results set when querying from the collection"""
    filter: SermonsFilter

    """Sort order to apply to the collection"""
    orderBy: [SermonsOrderBy!]
  ): SermonsConnection!
}

type Sermons implements Node {
  """Globally Unique Record Identifier"""
  nodeId: ID!
  id: UUID!
  title: String!
  preacher: String!
  preachedOn: Date!
  series: String
  scripture: String
  notes: String
  videoUrl: String
  audioPath: String
  publishAt: Datetime
}

type SermonsConnection {
  edges: [SermonsEdge!]!
  pageInfo: PageInfo!
}

type SermonsEdge {
  cursor: String!
  node: Sermons!
}

input SermonsFilter {
  id: UUIDFilter
  title: StringFilter
  preacher: StringFilter
  preachedOn: DateFilter
  series: StringFilter
  scripture: StringFilter
  notes: StringFilter
  videoUrl: StringFilter
  audioPath: StringFilter
  publishAt: DatetimeFilter
  nodeId: IDFilter

  """
  Returns true only if all its inner filters are true, otherwise returns false
  """
  and: [SermonsFilter!]

  """
  Returns true if at least one of its inner filters is true, otherwise returns false
  """
  or: [SermonsFilter!]

  """Negates a filter"""
  not: SermonsFilter
}

input SermonsOrderBy {
  id: OrderByDirection
  title: OrderByDirection
  preacher: OrderByDirection
  preachedOn: OrderByDirection
  series: OrderByDirection
  scripture: OrderByDirection
  notes: OrderByDirection
  videoUrl: OrderByDirection
  audioPath: OrderByDirection
  publishAt: OrderByDirection
}

enum ServiceType {
  sunday
  midweek
  special
  program
}

"""
Boolean expression comparing fields on type "ServiceType"
"""
input ServiceTypeFilter {
  eq: ServiceType
  in: [ServiceType!]
  is: FilterIs
  neq: ServiceType
}

"""
Boolean expression comparing fields on type "String"
"""
input StringFilter {
  eq: String
  gt: String
  gte: String
  ilike: String
  in: [String!]
  iregex: String
  is: FilterIs
  like: String
  lt: String
  lte: String
  neq: String
  regex: String
  startsWith: String
}

"""
Boolean expression comparing fields on type "StringList"
"""
input StringListFilter {
  containedBy: [String!]
  contains: [String!]
  eq: [String!]
  is: FilterIs
  overlaps: [String!]
}

"""A time without date information"""
scalar Time

"""
Boolean expression comparing fields on type "Time"
"""
input TimeFilter {
  eq: Time
  gt: Time
  gte: Time
  in: [Time!]
  is: FilterIs
  lt: Time
  lte: Time
  neq: Time
}

"""
Boolean expression comparing fields on type "TimeList"
"""
input TimeListFilter {
  containedBy: [Time!]
  contains: [Time!]
  eq: [Time!]
  is: FilterIs
  overlaps: [Time!]
}

"""A universally unique identifier"""
scalar UUID

"""
Boolean expression comparing fields on type "UUID"
"""
input UUIDFilter {
  eq: UUID
  in: [UUID!]
  is: FilterIs
  neq: UUID
}

"""
Boolean expression comparing fields on type "UUIDList"
"""
input UUIDListFilter {
  containedBy: [UUID!]
  contains: [UUID!]
  eq: [UUID!]
  is: FilterIs
  overlaps: [UUID!]
}
